category = {
    "General Knowledge":"9",
    "Entertainment: Books":"10",
    "Entertainment: Film": "11",
    "Entertainment: Music": "12",
    "Entertainment: Musicals & Theatres":"13",
    "Entertainment: Television": "14",
    "Entertainment: Video Games": "15",
    "Entertainment: Board Games": "16",
    "Science & Nature": "17",
    "Science: Computers":"18",
    "Science: Mathematics":"19",
    "Mythology": "20",
    "Sports":"21",
    "Geography":"22",
    "History":"23",
    "Politics":"24",
    "Art":"25",
    "Celebrities":"26",
    "Animals":"27",
    "Vehicles":"28",
    "Entertainment: Comics":"29",
    "Science: Gadgets":"30",
    "Entertainment: Japanese Anime & Manga":"32" ,
    "Entertainment: Cartoon & Animations":"33"
}

difficulty = ['easy','medium','hard']
option_list={
1 :"General Knowledge",
2 :"Entertainment: Books",
3 :"Entertainment: Film",
4 :"Entertainment: Music",
5 :"Entertainment: Musicals & Theatres",
6 :"Entertainment: Television",
7 :"Entertainment: Video Games",
8 :"Entertainment: Board Games",
9 :"Science & Nature",
10 :"Science: Computers",
11 :"Science: Mathematics",
12 :"Mythology",
13 :"Sports",
14 :"Geography",
15 :"History",
16 :"Politics",
17 :"Art",
18 :"Celebrities",
19 :"Animals",
20 :"Vehicles",
21 :"Entertainment: Comics",
22 :"Science: Gadgets",
23 :"Entertainment: Japanese Anime & Manga",
24 :"Entertainment: Cartoon & Animations"
}